# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 345)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.LabelTen = QtWidgets.QLabel(self.centralwidget)
        self.LabelTen.setGeometry(QtCore.QRect(100, 80, 101, 51))
        self.LabelTen.setIndent(9)
        self.LabelTen.setObjectName("LabelTen")
        self.ButLog = QtWidgets.QPushButton(self.centralwidget)
        self.ButLog.setGeometry(QtCore.QRect(280, 190, 75, 23))
        self.ButLog.setObjectName("ButLog")
        self.LabelMk = QtWidgets.QLabel(self.centralwidget)
        self.LabelMk.setGeometry(QtCore.QRect(120, 140, 71, 21))
        self.LabelMk.setObjectName("LabelMk")
        self.Ten = QtWidgets.QLineEdit(self.centralwidget)
        self.Ten.setGeometry(QtCore.QRect(210, 100, 231, 31))
        self.Ten.setObjectName("Ten")
        self.Matkhau = QtWidgets.QLineEdit(self.centralwidget)
        self.Matkhau.setGeometry(QtCore.QRect(210, 140, 231, 31))
        self.Matkhau.setObjectName("Matkhau")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.LabelTen.setText(_translate("MainWindow", "Tên đăng nhập"))
        self.ButLog.setText(_translate("MainWindow", "Login"))
        self.LabelMk.setText(_translate("MainWindow", "Mật khẩu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
