# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'using.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Cont = QtWidgets.QPushButton(self.centralwidget)
        self.Cont.setGeometry(QtCore.QRect(340, 300, 75, 23))
        self.Cont.setObjectName("Cont")
        self.LabelUse = QtWidgets.QLabel(self.centralwidget)
        self.LabelUse.setGeometry(QtCore.QRect(310, 190, 141, 91))
        self.LabelUse.setObjectName("LabelUse")
        self.LabelUse_2 = QtWidgets.QLabel(self.centralwidget)
        self.LabelUse_2.setGeometry(QtCore.QRect(280, 270, 211, 16))
        self.LabelUse_2.setObjectName("LabelUse_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Cont.setText(_translate("MainWindow", "Tiếp tục"))
        self.LabelUse.setText(_translate("MainWindow", "TỦ ĐANG ĐƯỢC SỬ DỤNG"))
        self.LabelUse_2.setText(_translate("MainWindow", "Nếu bạn muốn lấy đồ, vui lòng nhấn tiếp tục"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
